### ISSUE TITLE
Unable to resolve reference

### ISSUE THREAD

**Issue by afominov** [filwaline/Apollo-Federation-Mutation-Demo#1]
Hey there! I would like to test your approach for mutations but with example mutation from readme

```
mutation ExampleMutation($productId: String!, $body: String!) {
  review(productId: $productId){
    comment(body: $body) {
      id
      body
    }
  }
}
```

I got an error 

```
{
  "data": {},
  "errors": [
    {
      "message": "Unable to resolve reference for <class 'reviews.graphql.ReviewMutation'>",
      "locations": [
        {
          "line": 1,
          "column": 75
        }
      ],
      "path": [
        "review"
      ]
    }
  ],
  "extensions": {
    "valueCompletion": [
      {
        "message": "Cannot return null for non-nullable field ReviewMutation.comment",
        "path": [
          "review"
        ]
      },
      {
        "message": "Cannot return null for non-nullable field ReviewMutation!.review",
        "path": [
          "review"
        ]
      }
    ]
  }
}
```

Unfortunately, I'm not familiar with python and strawberry lib and I can't get what is the problem.

Thank you

**Comment by filwaline** [comment]
The error message you received indicates that one of the external subgraphs was unable to resolve. In your example, it may be due to a missing login information in the ReviewMutation.currentUser field. I apologize for not providing a clear error message earlier.

For a better understanding, here is a full example of the issue. I recommend trying to execute the code one step at a time: 
http://localhost:4000/?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4RxighigSwiQAIAZCAcwKQAoASGAZwQCcldF0SBlFVmpQCEAShLAAOqRIAbKjVrM2HLiUYt2nBGMnSSJAmCn79KhMZNLNiCwF8p9pFKkBHGGwCeJWK1bIUAKoa4haIIXoGRhFmFvpWMdKOjs5I2HiExCQAogAenAAOMggAsjj4RHT0%2BawQYDBQKACSYNx8AkjCADRqAEa1Hq38gqLh%2Bn4AbgQIAO601bX1TS1q83UNzSK6Jt4QcIiotH1gA739OrEmhhf6Rx7XJKuLo9smCS8mE1PTTM-v%2Brg4AAWEFYvz%2Bpi0922jnBN36UJIMJeSP0SKSIE6IHGuAEuB6RSYGBAWxIEhAtzJ3DJSAgKBIPVwYCEZM6FjJj3WRgwpJAAEYWWyQPFIdyyQABRm4AVIWwgWxAA

**Comment by afominov** [comment]
@filwaline Thank you! It works now! :)

I've recreated your approach in my example project with apollo-server.

Do you "invent" approach with @required directive for mutations by yourself? Never seen it in documentation for using with mutations in federated graphs. Do you use it in production systems?

**Comment by filwaline** [comment]
@afominov kind of :)

The official document, ["Contributing Computed Entity Fields"](https://www.apollographql.com/docs/federation/entities-advanced/#contributing-computed-entity-fields) inspired me. Since fields and mutations are almost identical and can be grouped under an object type, I thought, "Why not make them work as federated mutations?" So, I "invented" this approach. I am currently using this approach in production and everything is working well thus far.
